// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package repository

import (
	"context"
	"time"
)

const checkDuplicateTemplate = `-- name: CheckDuplicateTemplate :one
SELECT EXISTS (
    SELECT 1 
    FROM room_templates
    WHERE players_needed = $1
      AND min_players = $2
      AND entry_cost = $3
      AND winner_pct = $4
      AND game_type = $5
) AS duplicate_exists
`

type CheckDuplicateTemplateParams struct {
	PlayersNeeded int32  `json:"players_needed"`
	MinPlayers    int32  `json:"min_players"`
	EntryCost     int32  `json:"entry_cost"`
	WinnerPct     int32  `json:"winner_pct"`
	GameType      string `json:"game_type"`
}

func (q *Queries) CheckDuplicateTemplate(ctx context.Context, arg CheckDuplicateTemplateParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDuplicateTemplate,
		arg.PlayersNeeded,
		arg.MinPlayers,
		arg.EntryCost,
		arg.WinnerPct,
		arg.GameType,
	)
	var duplicate_exists bool
	err := row.Scan(&duplicate_exists)
	return duplicate_exists, err
}

const deleteRoomsByTemplate = `-- name: DeleteRoomsByTemplate :exec
DELETE FROM rooms
WHERE template_id = $1
  AND status IN ('finished', 'new')
`

type DeleteRoomsByTemplateParams struct {
	TemplateID *int32 `json:"template_id"`
}

func (q *Queries) DeleteRoomsByTemplate(ctx context.Context, arg DeleteRoomsByTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteRoomsByTemplate, arg.TemplateID)
	return err
}

const getBoostStatistics = `-- name: GetBoostStatistics :one
WITH boost_data AS (
    SELECT 
        SUM(rb.amount)::BIGINT AS total_boost_amount,
        COUNT(DISTINCT rb.user_id)::INTEGER AS total_players,
        COUNT(DISTINCT rb.room_id)::INTEGER AS total_rooms
    FROM room_boosts rb
    INNER JOIN rooms r ON rb.room_id = r.room_id
    WHERE r.template_id = $1
      AND rb.boosted_at >= $2
      AND rb.boosted_at <= $3
)
SELECT 
    COALESCE(total_boost_amount, 0)::BIGINT AS total_boost_amount,
    COALESCE(total_boost_amount::FLOAT / NULLIF(total_players, 0), 0)::FLOAT AS avg_boost_per_player,
    COALESCE(total_boost_amount::FLOAT / NULLIF(total_rooms, 0), 0)::FLOAT AS avg_boost_per_room
FROM boost_data
`

type GetBoostStatisticsParams struct {
	TemplateID  *int32    `json:"template_id"`
	BoostedAt   time.Time `json:"boosted_at"`
	BoostedAt_2 time.Time `json:"boosted_at_2"`
}

type GetBoostStatisticsRow struct {
	TotalBoostAmount  int64   `json:"total_boost_amount"`
	AvgBoostPerPlayer float64 `json:"avg_boost_per_player"`
	AvgBoostPerRoom   float64 `json:"avg_boost_per_room"`
}

func (q *Queries) GetBoostStatistics(ctx context.Context, arg GetBoostStatisticsParams) (GetBoostStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getBoostStatistics, arg.TemplateID, arg.BoostedAt, arg.BoostedAt_2)
	var i GetBoostStatisticsRow
	err := row.Scan(&i.TotalBoostAmount, &i.AvgBoostPerPlayer, &i.AvgBoostPerRoom)
	return i, err
}

const getHistoricalMetrics = `-- name: GetHistoricalMetrics :one
WITH completed_rooms AS (
    SELECT 
        r.room_id,
        r.entry_cost,
        COUNT(DISTINCT rp.user_id) FILTER (WHERE u.bot = false) AS real_players
    FROM rooms r
    LEFT JOIN room_players rp ON r.room_id = rp.room_id
    LEFT JOIN users u ON rp.user_id = u.id
    WHERE r.status = 'finished'
      AND r.created_at >= $1
    GROUP BY r.room_id, r.entry_cost
)
SELECT 
    COALESCE(AVG(real_players), 0)::FLOAT AS avg_real_players_per_room,
    COALESCE(AVG(entry_cost), 0)::FLOAT AS avg_entry_cost,
    COUNT(*)::BIGINT AS total_completed_rooms
FROM completed_rooms
`

type GetHistoricalMetricsParams struct {
	CreatedAt time.Time `json:"created_at"`
}

type GetHistoricalMetricsRow struct {
	AvgRealPlayersPerRoom float64 `json:"avg_real_players_per_room"`
	AvgEntryCost          float64 `json:"avg_entry_cost"`
	TotalCompletedRooms   int64   `json:"total_completed_rooms"`
}

func (q *Queries) GetHistoricalMetrics(ctx context.Context, arg GetHistoricalMetricsParams) (GetHistoricalMetricsRow, error) {
	row := q.db.QueryRow(ctx, getHistoricalMetrics, arg.CreatedAt)
	var i GetHistoricalMetricsRow
	err := row.Scan(&i.AvgRealPlayersPerRoom, &i.AvgEntryCost, &i.TotalCompletedRooms)
	return i, err
}

const getPlaceStatistics = `-- name: GetPlaceStatistics :one
WITH place_data AS (
    SELECT 
        COUNT(*)::INTEGER AS total_places,
        COUNT(DISTINCT rpl.user_id)::INTEGER AS total_players
    FROM room_places rpl
    INNER JOIN rooms r ON rpl.room_id = r.room_id
    WHERE r.template_id = $1
      AND rpl.created_at >= $2
      AND rpl.created_at <= $3
)
SELECT 
    COALESCE(total_places::FLOAT / NULLIF(total_players, 0), 0)::FLOAT AS avg_places_per_player
FROM place_data
`

type GetPlaceStatisticsParams struct {
	TemplateID  *int32    `json:"template_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) GetPlaceStatistics(ctx context.Context, arg GetPlaceStatisticsParams) (float64, error) {
	row := q.db.QueryRow(ctx, getPlaceStatistics, arg.TemplateID, arg.CreatedAt, arg.CreatedAt_2)
	var avg_places_per_player float64
	err := row.Scan(&avg_places_per_player)
	return avg_places_per_player, err
}

const getRoomsByTemplate = `-- name: GetRoomsByTemplate :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type, min_players, template_id FROM rooms
WHERE template_id = $1
`

type GetRoomsByTemplateParams struct {
	TemplateID *int32 `json:"template_id"`
}

func (q *Queries) GetRoomsByTemplate(ctx context.Context, arg GetRoomsByTemplateParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRoomsByTemplate, arg.TemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
			&i.WinnerPct,
			&i.RoundDurationSeconds,
			&i.StartDelaySeconds,
			&i.GameType,
			&i.MinPlayers,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateRoomStatus = `-- name: GetTemplateRoomStatus :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'playing')::INTEGER AS active_rooms,
    COUNT(*) FILTER (WHERE status IN ('new', 'starting_soon'))::INTEGER AS waiting_rooms
FROM rooms
WHERE template_id = $1
`

type GetTemplateRoomStatusParams struct {
	TemplateID *int32 `json:"template_id"`
}

type GetTemplateRoomStatusRow struct {
	ActiveRooms  int32 `json:"active_rooms"`
	WaitingRooms int32 `json:"waiting_rooms"`
}

func (q *Queries) GetTemplateRoomStatus(ctx context.Context, arg GetTemplateRoomStatusParams) (GetTemplateRoomStatusRow, error) {
	row := q.db.QueryRow(ctx, getTemplateRoomStatus, arg.TemplateID)
	var i GetTemplateRoomStatusRow
	err := row.Scan(&i.ActiveRooms, &i.WaitingRooms)
	return i, err
}

const getTemplateStatistics = `-- name: GetTemplateStatistics :one
WITH template_rooms AS (
    SELECT r.room_id
    FROM rooms r
    WHERE r.template_id = $1
      AND r.status = 'finished'
      AND r.created_at >= $2
      AND r.created_at <= $3
)
SELECT 
    COUNT(DISTINCT tr.room_id)::INTEGER AS completed_rooms,
    COUNT(DISTINCT rp.user_id) FILTER (WHERE u.bot = false)::INTEGER AS total_real_players,
    COUNT(DISTINCT rp.user_id) FILTER (WHERE u.bot = true)::INTEGER AS total_bots,
    COALESCE(
        COUNT(DISTINCT rp.user_id) FILTER (WHERE u.bot = false)::FLOAT / 
        NULLIF(COUNT(DISTINCT tr.room_id), 0), 
        0
    )::FLOAT AS avg_real_players_per_room
FROM template_rooms tr
LEFT JOIN room_players rp ON tr.room_id = rp.room_id
LEFT JOIN users u ON rp.user_id = u.id
`

type GetTemplateStatisticsParams struct {
	TemplateID  *int32    `json:"template_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetTemplateStatisticsRow struct {
	CompletedRooms        int32   `json:"completed_rooms"`
	TotalRealPlayers      int32   `json:"total_real_players"`
	TotalBots             int32   `json:"total_bots"`
	AvgRealPlayersPerRoom float64 `json:"avg_real_players_per_room"`
}

func (q *Queries) GetTemplateStatistics(ctx context.Context, arg GetTemplateStatisticsParams) (GetTemplateStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getTemplateStatistics, arg.TemplateID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetTemplateStatisticsRow
	err := row.Scan(
		&i.CompletedRooms,
		&i.TotalRealPlayers,
		&i.TotalBots,
		&i.AvgRealPlayersPerRoom,
	)
	return i, err
}

const getWinnerStatistics = `-- name: GetWinnerStatistics :one
SELECT 
    COUNT(*) FILTER (WHERE u.bot = false)::INTEGER AS real_player_wins,
    COUNT(*) FILTER (WHERE u.bot = true)::INTEGER AS bot_wins
FROM room_winners rw
INNER JOIN users u ON rw.user_id = u.id
INNER JOIN rooms r ON rw.room_id = r.room_id
WHERE r.template_id = $1
  AND rw.won_at >= $2
  AND rw.won_at <= $3
`

type GetWinnerStatisticsParams struct {
	TemplateID *int32    `json:"template_id"`
	WonAt      time.Time `json:"won_at"`
	WonAt_2    time.Time `json:"won_at_2"`
}

type GetWinnerStatisticsRow struct {
	RealPlayerWins int32 `json:"real_player_wins"`
	BotWins        int32 `json:"bot_wins"`
}

func (q *Queries) GetWinnerStatistics(ctx context.Context, arg GetWinnerStatisticsParams) (GetWinnerStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getWinnerStatistics, arg.TemplateID, arg.WonAt, arg.WonAt_2)
	var i GetWinnerStatisticsRow
	err := row.Scan(&i.RealPlayerWins, &i.BotWins)
	return i, err
}
