// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hello.sql

package repository

import (
	"context"
)

const greet = `-- name: Greet :one
SELECT 'Hello, ' || $1::text AS greeting
`

type GreetParams struct {
	Name string `json:"name"`
}

func (q *Queries) Greet(ctx context.Context, arg GreetParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, greet, arg.Name)
	var greeting interface{}
	err := row.Scan(&greeting)
	return greeting, err
}
