// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	RoomID        int32              `json:"room_id"`
	Jackpot       int32              `json:"jackpot"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	Status        string             `json:"status"`
	PlayersNeeded int32              `json:"players_needed"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	EntryCost     int32              `json:"entry_cost"`
}

type RoomBoost struct {
	RoomID    int32     `json:"room_id"`
	UserID    int32     `json:"user_id"`
	Amount    int32     `json:"amount"`
	BoostedAt time.Time `json:"boosted_at"`
}

type RoomPlayer struct {
	RoomID   int32     `json:"room_id"`
	UserID   int32     `json:"user_id"`
	Places   *int32    `json:"places"`
	JoinedAt time.Time `json:"joined_at"`
}

type RoomWinner struct {
	RoomID int32     `json:"room_id"`
	UserID int32     `json:"user_id"`
	Prize  int32     `json:"prize"`
	WonAt  time.Time `json:"won_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Balance   int32     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
	Bot       bool      `json:"bot"`
}
