// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMoneyToJackpot = `-- name: AddMoneyToJackpot :one
WITH user_balance AS (
    SELECT balance FROM users WHERE users.id = $3
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - $2
    WHERE users.id = $3 AND (SELECT balance FROM user_balance) >= $2
    RETURNING users.id
)
UPDATE rooms
SET jackpot = jackpot + $2, updated_at = CURRENT_TIMESTAMP
WHERE room_id = $1 AND EXISTS (SELECT 1 FROM balance_update)
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
`

type AddMoneyToJackpotParams struct {
	RoomID  int32 `json:"room_id"`
	Jackpot int32 `json:"jackpot"`
	ID      int32 `json:"id"`
}

func (q *Queries) AddMoneyToJackpot(ctx context.Context, arg AddMoneyToJackpotParams) (Room, error) {
	row := q.db.QueryRow(ctx, addMoneyToJackpot, arg.RoomID, arg.Jackpot, arg.ID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const botJoinRoom = `-- name: BotJoinRoom :many
WITH room_info AS (
    SELECT entry_cost, status, players_needed FROM rooms WHERE rooms.room_id = $1
),
user_info AS (
    SELECT balance, bot FROM users WHERE users.id = $2
),
current_player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_id = $1
),
inserted AS (
    INSERT INTO room_players (room_id, user_id, places)
    SELECT $1, $2, $3
    WHERE (SELECT balance FROM user_info) >= (SELECT entry_cost FROM room_info)
      AND (SELECT bot FROM user_info) = true
      AND NOT EXISTS (SELECT 1 FROM room_players WHERE room_id = $1 AND user_id = $2)
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon', 'playing')
      AND (SELECT count FROM current_player_count) < (SELECT players_needed FROM room_info)
    RETURNING room_id, user_id, places, joined_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = jackpot + (SELECT entry_cost FROM room_info), updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
)
SELECT room_id, user_id, places, joined_at FROM inserted
`

type BotJoinRoomParams struct {
	RoomID int32  `json:"room_id"`
	ID     int32  `json:"id"`
	Places *int32 `json:"places"`
}

type BotJoinRoomRow struct {
	RoomID   int32     `json:"room_id"`
	UserID   int32     `json:"user_id"`
	Places   *int32    `json:"places"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) BotJoinRoom(ctx context.Context, arg BotJoinRoomParams) ([]BotJoinRoomRow, error) {
	rows, err := q.db.Query(ctx, botJoinRoom, arg.RoomID, arg.ID, arg.Places)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotJoinRoomRow{}
	for rows.Next() {
		var i BotJoinRoomRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Places,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRoomPlayers = `-- name: CountRoomPlayers :one
SELECT COUNT(*) FROM room_players
WHERE room_id = $1
`

type CountRoomPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) CountRoomPlayers(ctx context.Context, arg CountRoomPlayersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomPlayers, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE room_id = $1
`

type DeleteRoomParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.RoomID)
	return err
}

const finishRoomAndAwardWinner = `-- name: FinishRoomAndAwardWinner :one
WITH finish_room AS (
    UPDATE rooms
    SET status = 'finished', updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND rooms.status = 'playing'
    RETURNING jackpot
),
award_winner AS (
    UPDATE users
    SET balance = users.balance + ($2 * 80 / 100)
    WHERE users.id = $3 AND EXISTS (SELECT 1 FROM finish_room)
    RETURNING users.id
),
insert_win AS (
    INSERT INTO room_winners (room_id, user_id, prize)
    SELECT $1, $3, ($2 * 80 / 100)
    WHERE EXISTS (SELECT 1 FROM finish_room)
    RETURNING room_id, user_id, prize, won_at
)
SELECT room_id, user_id, prize, won_at FROM insert_win
`

type FinishRoomAndAwardWinnerParams struct {
	RoomID  int32       `json:"room_id"`
	Column2 interface{} `json:"column_2"`
	ID      int32       `json:"id"`
}

type FinishRoomAndAwardWinnerRow struct {
	RoomID int32     `json:"room_id"`
	UserID int32     `json:"user_id"`
	Prize  int32     `json:"prize"`
	WonAt  time.Time `json:"won_at"`
}

func (q *Queries) FinishRoomAndAwardWinner(ctx context.Context, arg FinishRoomAndAwardWinnerParams) (FinishRoomAndAwardWinnerRow, error) {
	row := q.db.QueryRow(ctx, finishRoomAndAwardWinner, arg.RoomID, arg.Column2, arg.ID)
	var i FinishRoomAndAwardWinnerRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const finishRoomAndAwardWinnerPct = `-- name: FinishRoomAndAwardWinnerPct :one
WITH finish_room AS (
    UPDATE rooms
    SET status = 'finished', updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND rooms.status = 'playing'
    RETURNING jackpot, winner_pct
),
prize AS (
    SELECT (jackpot * winner_pct / 100) AS amount FROM finish_room
),
award_winner AS (
    UPDATE users
    SET balance = users.balance + (SELECT amount FROM prize)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM finish_room)
    RETURNING users.id
),
insert_win AS (
    INSERT INTO room_winners (room_id, user_id, prize)
    SELECT $1, $2, (SELECT amount FROM prize)
    WHERE EXISTS (SELECT 1 FROM finish_room)
    RETURNING room_id, user_id, prize, won_at
)
SELECT room_id, user_id, prize, won_at FROM insert_win
`

type FinishRoomAndAwardWinnerPctParams struct {
	RoomID int32 `json:"room_id"`
	ID     int32 `json:"id"`
}

type FinishRoomAndAwardWinnerPctRow struct {
	RoomID int32     `json:"room_id"`
	UserID int32     `json:"user_id"`
	Prize  int32     `json:"prize"`
	WonAt  time.Time `json:"won_at"`
}

func (q *Queries) FinishRoomAndAwardWinnerPct(ctx context.Context, arg FinishRoomAndAwardWinnerPctParams) (FinishRoomAndAwardWinnerPctRow, error) {
	row := q.db.QueryRow(ctx, finishRoomAndAwardWinnerPct, arg.RoomID, arg.ID)
	var i FinishRoomAndAwardWinnerPctRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const getAvailableBotsForRoom = `-- name: GetAvailableBotsForRoom :many
SELECT u.id, u.name, u.balance FROM users u
WHERE u.bot = true 
  AND u.balance >= $1
  AND NOT EXISTS (
    SELECT 1 FROM room_players rp WHERE rp.user_id = u.id AND rp.room_id = $2
  )
ORDER BY RANDOM()
LIMIT $3
`

type GetAvailableBotsForRoomParams struct {
	Balance int32 `json:"balance"`
	RoomID  int32 `json:"room_id"`
	Limit   int32 `json:"limit"`
}

type GetAvailableBotsForRoomRow struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Balance int32  `json:"balance"`
}

func (q *Queries) GetAvailableBotsForRoom(ctx context.Context, arg GetAvailableBotsForRoomParams) ([]GetAvailableBotsForRoomRow, error) {
	rows, err := q.db.Query(ctx, getAvailableBotsForRoom, arg.Balance, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableBotsForRoomRow{}
	for rows.Next() {
		var i GetAvailableBotsForRoomRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotsWithMinBalance = `-- name: GetBotsWithMinBalance :many
SELECT id, name, balance FROM users
WHERE bot = true AND balance >= $1
ORDER BY RANDOM()
LIMIT $2
`

type GetBotsWithMinBalanceParams struct {
	Balance int32 `json:"balance"`
	Limit   int32 `json:"limit"`
}

type GetBotsWithMinBalanceRow struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Balance int32  `json:"balance"`
}

func (q *Queries) GetBotsWithMinBalance(ctx context.Context, arg GetBotsWithMinBalanceParams) ([]GetBotsWithMinBalanceRow, error) {
	rows, err := q.db.Query(ctx, getBotsWithMinBalance, arg.Balance, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBotsWithMinBalanceRow{}
	for rows.Next() {
		var i GetBotsWithMinBalanceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersWithStakes = `-- name: GetPlayersWithStakes :many
SELECT
    rp.user_id,
    rp.places,
    COALESCE(rp.places, 1) * r.entry_cost AS stake,
    COALESCE(rb.amount, 0) AS boost_amount,
    COALESCE(rp.places, 1) * r.entry_cost + COALESCE(rb.amount, 0) AS total_stake
FROM room_players rp
JOIN rooms r ON r.room_id = rp.room_id
LEFT JOIN room_boosts rb ON rb.room_id = rp.room_id AND rb.user_id = rp.user_id
WHERE rp.room_id = $1
`

type GetPlayersWithStakesParams struct {
	RoomID int32 `json:"room_id"`
}

type GetPlayersWithStakesRow struct {
	UserID      int32  `json:"user_id"`
	Places      *int32 `json:"places"`
	Stake       int32  `json:"stake"`
	BoostAmount int32  `json:"boost_amount"`
	TotalStake  int32  `json:"total_stake"`
}

func (q *Queries) GetPlayersWithStakes(ctx context.Context, arg GetPlayersWithStakesParams) ([]GetPlayersWithStakesRow, error) {
	rows, err := q.db.Query(ctx, getPlayersWithStakes, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersWithStakesRow{}
	for rows.Next() {
		var i GetPlayersWithStakesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Places,
			&i.Stake,
			&i.BoostAmount,
			&i.TotalStake,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoom = `-- name: GetRoom :one
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type FROM rooms WHERE room_id = $1
`

type GetRoomParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetRoom(ctx context.Context, arg GetRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, arg.RoomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const getRoomWinner = `-- name: GetRoomWinner :one
SELECT room_id, user_id, prize, won_at FROM room_winners WHERE room_id = $1 AND user_id = $2
`

type GetRoomWinnerParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetRoomWinner(ctx context.Context, arg GetRoomWinnerParams) (RoomWinner, error) {
	row := q.db.QueryRow(ctx, getRoomWinner, arg.RoomID, arg.UserID)
	var i RoomWinner
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (jackpot, start_time, status, players_needed, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
`

type InsertRoomParams struct {
	Jackpot              int32              `json:"jackpot"`
	StartTime            pgtype.Timestamptz `json:"start_time"`
	Status               string             `json:"status"`
	PlayersNeeded        int32              `json:"players_needed"`
	EntryCost            int32              `json:"entry_cost"`
	WinnerPct            int32              `json:"winner_pct"`
	RoundDurationSeconds int32              `json:"round_duration_seconds"`
	StartDelaySeconds    int32              `json:"start_delay_seconds"`
	GameType             string             `json:"game_type"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, insertRoom,
		arg.Jackpot,
		arg.StartTime,
		arg.Status,
		arg.PlayersNeeded,
		arg.EntryCost,
		arg.WinnerPct,
		arg.RoundDurationSeconds,
		arg.StartDelaySeconds,
		arg.GameType,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const insertRoomBoost = `-- name: InsertRoomBoost :one
WITH room_status AS (
    SELECT status FROM rooms WHERE rooms.room_id = $1
),
user_balance_check AS (
    SELECT balance FROM users WHERE users.id = $2
),
inserted AS (
    INSERT INTO room_boosts (room_id, user_id, amount)
    SELECT $1, $2, $3
    WHERE (SELECT status FROM room_status) = 'playing'
      AND (SELECT balance FROM user_balance_check) >= $3
      AND $3 > 0
    RETURNING room_id, user_id, amount, boosted_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - $3
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = jackpot + $3, updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
)
SELECT room_id, user_id, amount, boosted_at FROM inserted
`

type InsertRoomBoostParams struct {
	RoomID int32 `json:"room_id"`
	ID     int32 `json:"id"`
	Amount int32 `json:"amount"`
}

type InsertRoomBoostRow struct {
	RoomID    int32     `json:"room_id"`
	UserID    int32     `json:"user_id"`
	Amount    int32     `json:"amount"`
	BoostedAt time.Time `json:"boosted_at"`
}

func (q *Queries) InsertRoomBoost(ctx context.Context, arg InsertRoomBoostParams) (InsertRoomBoostRow, error) {
	row := q.db.QueryRow(ctx, insertRoomBoost, arg.RoomID, arg.ID, arg.Amount)
	var i InsertRoomBoostRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Amount,
		&i.BoostedAt,
	)
	return i, err
}

const insertRoomWin = `-- name: InsertRoomWin :one
WITH room_info AS (
    SELECT status, jackpot FROM rooms WHERE rooms.room_id = $1
),
player_check AS (
    SELECT 1 FROM room_players WHERE room_players.room_id = $1 AND room_players.user_id = $2
),
inserted AS (
    INSERT INTO room_winners (room_id, user_id, prize)
    SELECT $1, $2, $3
    WHERE (SELECT status FROM room_info) = 'finished'
      AND EXISTS (SELECT 1 FROM player_check)
      AND $3 > 0
      AND $3 <= (SELECT jackpot FROM room_info)
    RETURNING room_id, user_id, prize, won_at
)
SELECT room_id, user_id, prize, won_at FROM inserted
`

type InsertRoomWinParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
	Prize  int32 `json:"prize"`
}

type InsertRoomWinRow struct {
	RoomID int32     `json:"room_id"`
	UserID int32     `json:"user_id"`
	Prize  int32     `json:"prize"`
	WonAt  time.Time `json:"won_at"`
}

func (q *Queries) InsertRoomWin(ctx context.Context, arg InsertRoomWinParams) (InsertRoomWinRow, error) {
	row := q.db.QueryRow(ctx, insertRoomWin, arg.RoomID, arg.UserID, arg.Prize)
	var i InsertRoomWinRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const joinRoom = `-- name: JoinRoom :one
WITH room_info AS (
    SELECT entry_cost, status, players_needed FROM rooms WHERE rooms.room_id = $1
),
user_balance AS (
    SELECT balance FROM users WHERE users.id = $2
),
current_player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_id = $1
),
inserted AS (
    INSERT INTO room_players (room_id, user_id, places)
    SELECT $1, $2, $3
    WHERE (SELECT balance FROM user_balance) >= (SELECT entry_cost FROM room_info)
      AND NOT EXISTS (SELECT 1 FROM room_players WHERE room_id = $1 AND user_id = $2)
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
      AND (SELECT count FROM current_player_count) < (SELECT players_needed FROM room_info)
    RETURNING room_id, user_id, places, joined_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = jackpot + (SELECT entry_cost FROM room_info), updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
)
SELECT room_id, user_id, places, joined_at FROM inserted
`

type JoinRoomParams struct {
	RoomID int32  `json:"room_id"`
	ID     int32  `json:"id"`
	Places *int32 `json:"places"`
}

type JoinRoomRow struct {
	RoomID   int32     `json:"room_id"`
	UserID   int32     `json:"user_id"`
	Places   *int32    `json:"places"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) (JoinRoomRow, error) {
	row := q.db.QueryRow(ctx, joinRoom, arg.RoomID, arg.ID, arg.Places)
	var i JoinRoomRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Places,
		&i.JoinedAt,
	)
	return i, err
}

const joinRoomAndUpdateStatus = `-- name: JoinRoomAndUpdateStatus :one
WITH room_info AS (
    SELECT entry_cost, status, players_needed, start_delay_seconds FROM rooms WHERE rooms.room_id = $1
),
user_balance AS (
    SELECT balance FROM users WHERE users.id = $2
),
current_player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_id = $1
),
inserted AS (
    INSERT INTO room_players (room_id, user_id, places)
    SELECT $1, $2, $3
    WHERE (SELECT balance FROM user_balance) >= (SELECT entry_cost FROM room_info)
      AND NOT EXISTS (SELECT 1 FROM room_players WHERE room_id = $1 AND user_id = $2)
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
      AND (SELECT count FROM current_player_count) < (SELECT players_needed FROM room_info)
    RETURNING room_id, user_id, places, joined_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_players.room_id = $1
)
UPDATE rooms
SET status = CASE 
    WHEN (SELECT status FROM room_info) = 'new' AND EXISTS (SELECT 1 FROM inserted) THEN 'starting_soon'
    ELSE status
END,
start_time = CASE
    WHEN (SELECT status FROM room_info) = 'new' AND (SELECT count FROM current_player_count) = 0 AND EXISTS (SELECT 1 FROM inserted) THEN CURRENT_TIMESTAMP + (SELECT start_delay_seconds FROM room_info) * INTERVAL '1 second'
    ELSE start_time
END,
jackpot = CASE
    WHEN EXISTS (SELECT 1 FROM inserted) THEN jackpot + (SELECT entry_cost FROM room_info)
    ELSE jackpot
END,
updated_at = CURRENT_TIMESTAMP
WHERE rooms.room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
`

type JoinRoomAndUpdateStatusParams struct {
	RoomID int32  `json:"room_id"`
	ID     int32  `json:"id"`
	Places *int32 `json:"places"`
}

func (q *Queries) JoinRoomAndUpdateStatus(ctx context.Context, arg JoinRoomAndUpdateStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, joinRoomAndUpdateStatus, arg.RoomID, arg.ID, arg.Places)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const leaveRoom = `-- name: LeaveRoom :one
WITH room_info AS (
    SELECT entry_cost, status FROM rooms WHERE rooms.room_id = $1
),
deleted AS (
    DELETE FROM room_players
    WHERE room_id = $1 AND user_id = $2
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
    RETURNING room_id, user_id, places, joined_at
),
balance_refund AS (
    UPDATE users
    SET balance = users.balance + (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM deleted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = GREATEST(jackpot - (SELECT entry_cost FROM room_info), 0), updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM deleted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
)
SELECT room_id, user_id, places, joined_at FROM deleted
`

type LeaveRoomParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

type LeaveRoomRow struct {
	RoomID   int32     `json:"room_id"`
	UserID   int32     `json:"user_id"`
	Places   *int32    `json:"places"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) (LeaveRoomRow, error) {
	row := q.db.QueryRow(ctx, leaveRoom, arg.RoomID, arg.UserID)
	var i LeaveRoomRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Places,
		&i.JoinedAt,
	)
	return i, err
}

const leaveRoomAndUpdateStatus = `-- name: LeaveRoomAndUpdateStatus :one
WITH room_info AS (
    SELECT entry_cost, status FROM rooms WHERE rooms.room_id = $1
),
deleted AS (
    DELETE FROM room_players
    WHERE room_players.room_id = $1 AND room_players.user_id = $2
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
    RETURNING room_id, user_id, places, joined_at
),
balance_refund AS (
    UPDATE users
    SET balance = users.balance + (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM deleted)
    RETURNING users.id
),
player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_players.room_id = $1
)
UPDATE rooms
SET status = CASE 
    WHEN (SELECT status FROM room_info) IN ('new', 'starting_soon') AND (SELECT count FROM player_count) = 0 THEN 'new'
    ELSE status
END,
jackpot = CASE
    WHEN EXISTS (SELECT 1 FROM deleted) THEN GREATEST(jackpot - (SELECT entry_cost FROM room_info), 0)
    ELSE jackpot
END,
updated_at = CURRENT_TIMESTAMP
WHERE rooms.room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
`

type LeaveRoomAndUpdateStatusParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) LeaveRoomAndUpdateStatus(ctx context.Context, arg LeaveRoomAndUpdateStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, leaveRoomAndUpdateStatus, arg.RoomID, arg.UserID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const listPlayingRoomsReadyToFinish = `-- name: ListPlayingRoomsReadyToFinish :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type FROM rooms
WHERE status = 'playing'
  AND start_time IS NOT NULL
  AND start_time + (round_duration_seconds * INTERVAL '1 second') <= CURRENT_TIMESTAMP
`

func (q *Queries) ListPlayingRoomsReadyToFinish(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listPlayingRoomsReadyToFinish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
			&i.WinnerPct,
			&i.RoundDurationSeconds,
			&i.StartDelaySeconds,
			&i.GameType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomBoosts = `-- name: ListRoomBoosts :many
SELECT room_id, user_id, amount, boosted_at FROM room_boosts
WHERE room_id = $1
ORDER BY boosted_at DESC
`

type ListRoomBoostsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomBoosts(ctx context.Context, arg ListRoomBoostsParams) ([]RoomBoost, error) {
	rows, err := q.db.Query(ctx, listRoomBoosts, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomBoost{}
	for rows.Next() {
		var i RoomBoost
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Amount,
			&i.BoostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT room_id, user_id, places, joined_at FROM room_players
WHERE room_id = $1
ORDER BY joined_at ASC
`

type ListRoomPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomPlayers(ctx context.Context, arg ListRoomPlayersParams) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPlayer{}
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Places,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomWins = `-- name: ListRoomWins :many
SELECT room_id, user_id, prize, won_at FROM room_winners
WHERE room_id = $1
ORDER BY won_at DESC
`

type ListRoomWinsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomWins(ctx context.Context, arg ListRoomWinsParams) ([]RoomWinner, error) {
	rows, err := q.db.Query(ctx, listRoomWins, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomWinner{}
	for rows.Next() {
		var i RoomWinner
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Prize,
			&i.WonAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
			&i.WinnerPct,
			&i.RoundDurationSeconds,
			&i.StartDelaySeconds,
			&i.GameType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsFiltered = `-- name: ListRoomsFiltered :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type FROM rooms
WHERE ($1::varchar = '' OR status = $1)
  AND ($2::integer = 0 OR entry_cost = $2)
  AND ($3::integer = 0 OR players_needed = $3)
ORDER BY
  CASE WHEN $4 = 'entry_cost'     AND $5 = 'asc'  THEN entry_cost     END ASC,
  CASE WHEN $4 = 'entry_cost'     AND $5 = 'desc' THEN entry_cost     END DESC,
  CASE WHEN $4 = 'jackpot'        AND $5 = 'asc'  THEN jackpot        END ASC,
  CASE WHEN $4 = 'jackpot'        AND $5 = 'desc' THEN jackpot        END DESC,
  CASE WHEN $4 = 'players_needed' AND $5 = 'asc'  THEN players_needed END ASC,
  CASE WHEN $4 = 'players_needed' AND $5 = 'desc' THEN players_needed END DESC,
  created_at DESC
`

type ListRoomsFilteredParams struct {
	Column1 string      `json:"column_1"`
	Column2 int32       `json:"column_2"`
	Column3 int32       `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) ListRoomsFiltered(ctx context.Context, arg ListRoomsFilteredParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
			&i.WinnerPct,
			&i.RoundDurationSeconds,
			&i.StartDelaySeconds,
			&i.GameType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomStatus = `-- name: SetRoomStatus :one
UPDATE rooms
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type
`

type SetRoomStatusParams struct {
	RoomID int32  `json:"room_id"`
	Status string `json:"status"`
}

func (q *Queries) SetRoomStatus(ctx context.Context, arg SetRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomStatus, arg.RoomID, arg.Status)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}
