// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMoneyToJackpot = `-- name: AddMoneyToJackpot :one
UPDATE rooms
SET jackpot = jackpot + $2, updated_at = CURRENT_TIMESTAMP
WHERE room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at
`

type AddMoneyToJackpotParams struct {
	RoomID  int32          `json:"room_id"`
	Jackpot pgtype.Numeric `json:"jackpot"`
}

func (q *Queries) AddMoneyToJackpot(ctx context.Context, arg AddMoneyToJackpotParams) (Room, error) {
	row := q.db.QueryRow(ctx, addMoneyToJackpot, arg.RoomID, arg.Jackpot)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE room_id = $1
`

type DeleteRoomParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.RoomID)
	return err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (jackpot, start_time, status, players_needed)
VALUES ($1, $2, $3, $4)
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at
`

type InsertRoomParams struct {
	Jackpot       pgtype.Numeric   `json:"jackpot"`
	StartTime     pgtype.Timestamp `json:"start_time"`
	Status        string           `json:"status"`
	PlayersNeeded int32            `json:"players_needed"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, insertRoom,
		arg.Jackpot,
		arg.StartTime,
		arg.Status,
		arg.PlayersNeeded,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoomBoost = `-- name: InsertRoomBoost :one
INSERT INTO room_boosts (room_id, user_id, amount)
VALUES ($1, $2, $3)
RETURNING room_id, user_id, amount, boosted_at
`

type InsertRoomBoostParams struct {
	RoomID int32          `json:"room_id"`
	UserID int32          `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) InsertRoomBoost(ctx context.Context, arg InsertRoomBoostParams) (RoomBoost, error) {
	row := q.db.QueryRow(ctx, insertRoomBoost, arg.RoomID, arg.UserID, arg.Amount)
	var i RoomBoost
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Amount,
		&i.BoostedAt,
	)
	return i, err
}

const insertRoomWin = `-- name: InsertRoomWin :one
INSERT INTO room_winners (room_id, user_id, prize)
VALUES ($1, $2, $3)
RETURNING room_id, user_id, prize, won_at
`

type InsertRoomWinParams struct {
	RoomID int32          `json:"room_id"`
	UserID int32          `json:"user_id"`
	Prize  pgtype.Numeric `json:"prize"`
}

func (q *Queries) InsertRoomWin(ctx context.Context, arg InsertRoomWinParams) (RoomWinner, error) {
	row := q.db.QueryRow(ctx, insertRoomWin, arg.RoomID, arg.UserID, arg.Prize)
	var i RoomWinner
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const joinRoom = `-- name: JoinRoom :one
INSERT INTO room_players (room_id, user_id, places)
VALUES ($1, $2, $3)
RETURNING room_id, user_id, places, joined_at
`

type JoinRoomParams struct {
	RoomID int32  `json:"room_id"`
	UserID int32  `json:"user_id"`
	Places *int32 `json:"places"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, joinRoom, arg.RoomID, arg.UserID, arg.Places)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Places,
		&i.JoinedAt,
	)
	return i, err
}

const leaveRoom = `-- name: LeaveRoom :exec
DELETE FROM room_players
WHERE room_id = $1 AND user_id = $2
`

type LeaveRoomParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) error {
	_, err := q.db.Exec(ctx, leaveRoom, arg.RoomID, arg.UserID)
	return err
}

const listRoomBoosts = `-- name: ListRoomBoosts :many
SELECT room_id, user_id, amount, boosted_at FROM room_boosts
WHERE room_id = $1
ORDER BY boosted_at DESC
`

type ListRoomBoostsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomBoosts(ctx context.Context, arg ListRoomBoostsParams) ([]RoomBoost, error) {
	rows, err := q.db.Query(ctx, listRoomBoosts, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomBoost{}
	for rows.Next() {
		var i RoomBoost
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Amount,
			&i.BoostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT room_id, user_id, places, joined_at FROM room_players
WHERE room_id = $1
ORDER BY joined_at ASC
`

type ListRoomPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomPlayers(ctx context.Context, arg ListRoomPlayersParams) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPlayer{}
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Places,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomWins = `-- name: ListRoomWins :many
SELECT room_id, user_id, prize, won_at FROM room_winners
WHERE room_id = $1
ORDER BY won_at DESC
`

type ListRoomWinsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomWins(ctx context.Context, arg ListRoomWinsParams) ([]RoomWinner, error) {
	rows, err := q.db.Query(ctx, listRoomWins, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomWinner{}
	for rows.Next() {
		var i RoomWinner
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Prize,
			&i.WonAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomStatus = `-- name: SetRoomStatus :one
UPDATE rooms
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at
`

type SetRoomStatusParams struct {
	RoomID int32  `json:"room_id"`
	Status string `json:"status"`
}

func (q *Queries) SetRoomStatus(ctx context.Context, arg SetRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomStatus, arg.RoomID, arg.Status)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
