// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMoneyToJackpot = `-- name: AddMoneyToJackpot :one
WITH user_balance AS (
    SELECT balance FROM users WHERE users.id = $3
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - $2
    WHERE users.id = $3 AND (SELECT balance FROM user_balance) >= $2
    RETURNING users.id
)
UPDATE rooms
SET jackpot = jackpot + $2, updated_at = CURRENT_TIMESTAMP
WHERE room_id = $1 AND EXISTS (SELECT 1 FROM balance_update)
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
`

type AddMoneyToJackpotParams struct {
	RoomID  int32          `json:"room_id"`
	Jackpot pgtype.Numeric `json:"jackpot"`
	ID      int32          `json:"id"`
}

func (q *Queries) AddMoneyToJackpot(ctx context.Context, arg AddMoneyToJackpotParams) (Room, error) {
	row := q.db.QueryRow(ctx, addMoneyToJackpot, arg.RoomID, arg.Jackpot, arg.ID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
	)
	return i, err
}

const botJoinRoom = `-- name: BotJoinRoom :one
WITH room_info AS (
    SELECT entry_cost, status, players_needed FROM rooms WHERE rooms.room_id = $1
),
user_info AS (
    SELECT balance, bot FROM users WHERE users.id = $2
),
current_player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_id = $1
),
inserted AS (
    INSERT INTO room_players (room_id, user_id, places)
    SELECT $1, $2, $3
    WHERE (SELECT balance FROM user_info) >= (SELECT entry_cost FROM room_info)
      AND (SELECT bot FROM user_info) = true
      AND NOT EXISTS (SELECT 1 FROM room_players WHERE room_id = $1 AND user_id = $2)
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon', 'playing')
      AND (SELECT count FROM current_player_count) < (SELECT players_needed FROM room_info)
    RETURNING room_id, user_id, places, joined_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = jackpot + (SELECT entry_cost FROM room_info), updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
)
SELECT room_id, user_id, places, joined_at FROM inserted
`

type BotJoinRoomParams struct {
	RoomID int32  `json:"room_id"`
	ID     int32  `json:"id"`
	Places *int32 `json:"places"`
}

type BotJoinRoomRow struct {
	RoomID   int32            `json:"room_id"`
	UserID   int32            `json:"user_id"`
	Places   *int32           `json:"places"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) BotJoinRoom(ctx context.Context, arg BotJoinRoomParams) (BotJoinRoomRow, error) {
	row := q.db.QueryRow(ctx, botJoinRoom, arg.RoomID, arg.ID, arg.Places)
	var i BotJoinRoomRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Places,
		&i.JoinedAt,
	)
	return i, err
}

const countRoomPlayers = `-- name: CountRoomPlayers :one
SELECT COUNT(*) FROM room_players
WHERE room_id = $1
`

type CountRoomPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) CountRoomPlayers(ctx context.Context, arg CountRoomPlayersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomPlayers, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE room_id = $1
`

type DeleteRoomParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.RoomID)
	return err
}

const getBotsWithMinBalance = `-- name: GetBotsWithMinBalance :many
SELECT id, name, balance FROM users
WHERE bot = true AND balance >= $1
ORDER BY RANDOM()
LIMIT $2
`

type GetBotsWithMinBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	Limit   int32          `json:"limit"`
}

type GetBotsWithMinBalanceRow struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) GetBotsWithMinBalance(ctx context.Context, arg GetBotsWithMinBalanceParams) ([]GetBotsWithMinBalanceRow, error) {
	rows, err := q.db.Query(ctx, getBotsWithMinBalance, arg.Balance, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBotsWithMinBalanceRow{}
	for rows.Next() {
		var i GetBotsWithMinBalanceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (jackpot, start_time, status, players_needed, entry_cost)
VALUES ($1, $2, $3, $4, $5)
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
`

type InsertRoomParams struct {
	Jackpot       pgtype.Numeric   `json:"jackpot"`
	StartTime     pgtype.Timestamp `json:"start_time"`
	Status        string           `json:"status"`
	PlayersNeeded int32            `json:"players_needed"`
	EntryCost     pgtype.Numeric   `json:"entry_cost"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, insertRoom,
		arg.Jackpot,
		arg.StartTime,
		arg.Status,
		arg.PlayersNeeded,
		arg.EntryCost,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
	)
	return i, err
}

const insertRoomBoost = `-- name: InsertRoomBoost :one
WITH room_status AS (
    SELECT status FROM rooms WHERE rooms.room_id = $1
),
user_balance_check AS (
    SELECT balance FROM users WHERE users.id = $2
),
inserted AS (
    INSERT INTO room_boosts (room_id, user_id, amount)
    SELECT $1, $2, $3
    WHERE (SELECT status FROM room_status) = 'playing'
      AND (SELECT balance FROM user_balance_check) >= $3
      AND $3 > 0
    RETURNING room_id, user_id, amount, boosted_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - $3
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = jackpot + $3, updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
)
SELECT room_id, user_id, amount, boosted_at FROM inserted
`

type InsertRoomBoostParams struct {
	RoomID int32          `json:"room_id"`
	ID     int32          `json:"id"`
	Amount pgtype.Numeric `json:"amount"`
}

type InsertRoomBoostRow struct {
	RoomID    int32            `json:"room_id"`
	UserID    int32            `json:"user_id"`
	Amount    pgtype.Numeric   `json:"amount"`
	BoostedAt pgtype.Timestamp `json:"boosted_at"`
}

func (q *Queries) InsertRoomBoost(ctx context.Context, arg InsertRoomBoostParams) (InsertRoomBoostRow, error) {
	row := q.db.QueryRow(ctx, insertRoomBoost, arg.RoomID, arg.ID, arg.Amount)
	var i InsertRoomBoostRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Amount,
		&i.BoostedAt,
	)
	return i, err
}

const insertRoomWin = `-- name: InsertRoomWin :one
WITH room_info AS (
    SELECT status, jackpot FROM rooms WHERE rooms.room_id = $1
),
player_check AS (
    SELECT 1 FROM room_players WHERE room_players.room_id = $1 AND room_players.user_id = $2
),
inserted AS (
    INSERT INTO room_winners (room_id, user_id, prize)
    SELECT $1, $2, $3
    WHERE (SELECT status FROM room_info) = 'finished'
      AND EXISTS (SELECT 1 FROM player_check)
      AND $3 > 0
      AND $3 <= (SELECT jackpot FROM room_info)
    RETURNING room_id, user_id, prize, won_at
)
SELECT room_id, user_id, prize, won_at FROM inserted
`

type InsertRoomWinParams struct {
	RoomID int32          `json:"room_id"`
	UserID int32          `json:"user_id"`
	Prize  pgtype.Numeric `json:"prize"`
}

type InsertRoomWinRow struct {
	RoomID int32            `json:"room_id"`
	UserID int32            `json:"user_id"`
	Prize  pgtype.Numeric   `json:"prize"`
	WonAt  pgtype.Timestamp `json:"won_at"`
}

func (q *Queries) InsertRoomWin(ctx context.Context, arg InsertRoomWinParams) (InsertRoomWinRow, error) {
	row := q.db.QueryRow(ctx, insertRoomWin, arg.RoomID, arg.UserID, arg.Prize)
	var i InsertRoomWinRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const joinRoom = `-- name: JoinRoom :one
WITH room_info AS (
    SELECT entry_cost, status, players_needed FROM rooms WHERE rooms.room_id = $1
),
user_balance AS (
    SELECT balance FROM users WHERE users.id = $2
),
current_player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_id = $1
),
inserted AS (
    INSERT INTO room_players (room_id, user_id, places)
    SELECT $1, $2, $3
    WHERE (SELECT balance FROM user_balance) >= (SELECT entry_cost FROM room_info)
      AND NOT EXISTS (SELECT 1 FROM room_players WHERE room_id = $1 AND user_id = $2)
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
      AND (SELECT count FROM current_player_count) < (SELECT players_needed FROM room_info)
    RETURNING room_id, user_id, places, joined_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = jackpot + (SELECT entry_cost FROM room_info), updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
)
SELECT room_id, user_id, places, joined_at FROM inserted
`

type JoinRoomParams struct {
	RoomID int32  `json:"room_id"`
	ID     int32  `json:"id"`
	Places *int32 `json:"places"`
}

type JoinRoomRow struct {
	RoomID   int32            `json:"room_id"`
	UserID   int32            `json:"user_id"`
	Places   *int32           `json:"places"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) (JoinRoomRow, error) {
	row := q.db.QueryRow(ctx, joinRoom, arg.RoomID, arg.ID, arg.Places)
	var i JoinRoomRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Places,
		&i.JoinedAt,
	)
	return i, err
}

const joinRoomAndUpdateStatus = `-- name: JoinRoomAndUpdateStatus :one
WITH room_info AS (
    SELECT entry_cost, status, players_needed FROM rooms WHERE rooms.room_id = $1
),
user_balance AS (
    SELECT balance FROM users WHERE users.id = $2
),
current_player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_id = $1
),
inserted AS (
    INSERT INTO room_players (room_id, user_id, places)
    SELECT $1, $2, $3
    WHERE (SELECT balance FROM user_balance) >= (SELECT entry_cost FROM room_info)
      AND NOT EXISTS (SELECT 1 FROM room_players WHERE room_id = $1 AND user_id = $2)
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
      AND (SELECT count FROM current_player_count) < (SELECT players_needed FROM room_info)
    RETURNING room_id, user_id, places, joined_at
),
balance_update AS (
    UPDATE users
    SET balance = users.balance - (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM inserted)
    RETURNING users.id
),
player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_players.room_id = $1
)
UPDATE rooms
SET status = CASE 
    WHEN (SELECT status FROM room_info) = 'new' AND (SELECT count FROM player_count) > 0 THEN 'starting_soon'
    ELSE status
END,
start_time = CASE
    WHEN (SELECT status FROM room_info) = 'new' AND (SELECT count FROM player_count) = 1 THEN CURRENT_TIMESTAMP + INTERVAL '1 minute'
    ELSE start_time
END,
jackpot = CASE
    WHEN EXISTS (SELECT 1 FROM inserted) THEN jackpot + (SELECT entry_cost FROM room_info)
    ELSE jackpot
END,
updated_at = CURRENT_TIMESTAMP
WHERE rooms.room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
`

type JoinRoomAndUpdateStatusParams struct {
	RoomID int32  `json:"room_id"`
	ID     int32  `json:"id"`
	Places *int32 `json:"places"`
}

func (q *Queries) JoinRoomAndUpdateStatus(ctx context.Context, arg JoinRoomAndUpdateStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, joinRoomAndUpdateStatus, arg.RoomID, arg.ID, arg.Places)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
	)
	return i, err
}

const leaveRoom = `-- name: LeaveRoom :one
WITH room_info AS (
    SELECT entry_cost, status FROM rooms WHERE rooms.room_id = $1
),
deleted AS (
    DELETE FROM room_players
    WHERE room_id = $1 AND user_id = $2
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
    RETURNING room_id, user_id, places, joined_at
),
balance_refund AS (
    UPDATE users
    SET balance = users.balance + (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM deleted)
    RETURNING users.id
),
jackpot_update AS (
    UPDATE rooms
    SET jackpot = GREATEST(jackpot - (SELECT entry_cost FROM room_info), 0), updated_at = CURRENT_TIMESTAMP
    WHERE rooms.room_id = $1 AND EXISTS (SELECT 1 FROM deleted)
    RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
)
SELECT room_id, user_id, places, joined_at FROM deleted
`

type LeaveRoomParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

type LeaveRoomRow struct {
	RoomID   int32            `json:"room_id"`
	UserID   int32            `json:"user_id"`
	Places   *int32           `json:"places"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) (LeaveRoomRow, error) {
	row := q.db.QueryRow(ctx, leaveRoom, arg.RoomID, arg.UserID)
	var i LeaveRoomRow
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Places,
		&i.JoinedAt,
	)
	return i, err
}

const leaveRoomAndUpdateStatus = `-- name: LeaveRoomAndUpdateStatus :one
WITH room_info AS (
    SELECT entry_cost, status FROM rooms WHERE rooms.room_id = $1
),
deleted AS (
    DELETE FROM room_players
    WHERE room_players.room_id = $1 AND room_players.user_id = $2
      AND (SELECT status FROM room_info) IN ('new', 'starting_soon')
    RETURNING room_id, user_id, places, joined_at
),
balance_refund AS (
    UPDATE users
    SET balance = users.balance + (SELECT entry_cost FROM room_info)
    WHERE users.id = $2 AND EXISTS (SELECT 1 FROM deleted)
    RETURNING users.id
),
player_count AS (
    SELECT COUNT(*) as count FROM room_players WHERE room_players.room_id = $1
)
UPDATE rooms
SET status = CASE 
    WHEN (SELECT status FROM room_info) IN ('new', 'starting_soon') AND (SELECT count FROM player_count) = 0 THEN 'new'
    ELSE status
END,
jackpot = CASE
    WHEN EXISTS (SELECT 1 FROM deleted) THEN GREATEST(jackpot - (SELECT entry_cost FROM room_info), 0)
    ELSE jackpot
END,
updated_at = CURRENT_TIMESTAMP
WHERE rooms.room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
`

type LeaveRoomAndUpdateStatusParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) LeaveRoomAndUpdateStatus(ctx context.Context, arg LeaveRoomAndUpdateStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, leaveRoomAndUpdateStatus, arg.RoomID, arg.UserID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
	)
	return i, err
}

const listRoomBoosts = `-- name: ListRoomBoosts :many
SELECT room_id, user_id, amount, boosted_at FROM room_boosts
WHERE room_id = $1
ORDER BY boosted_at DESC
`

type ListRoomBoostsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomBoosts(ctx context.Context, arg ListRoomBoostsParams) ([]RoomBoost, error) {
	rows, err := q.db.Query(ctx, listRoomBoosts, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomBoost{}
	for rows.Next() {
		var i RoomBoost
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Amount,
			&i.BoostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT room_id, user_id, places, joined_at FROM room_players
WHERE room_id = $1
ORDER BY joined_at ASC
`

type ListRoomPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomPlayers(ctx context.Context, arg ListRoomPlayersParams) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPlayer{}
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Places,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomWins = `-- name: ListRoomWins :many
SELECT room_id, user_id, prize, won_at FROM room_winners
WHERE room_id = $1
ORDER BY won_at DESC
`

type ListRoomWinsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) ListRoomWins(ctx context.Context, arg ListRoomWinsParams) ([]RoomWinner, error) {
	rows, err := q.db.Query(ctx, listRoomWins, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomWinner{}
	for rows.Next() {
		var i RoomWinner
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Prize,
			&i.WonAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomStatus = `-- name: SetRoomStatus :one
UPDATE rooms
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE room_id = $1
RETURNING room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost
`

type SetRoomStatusParams struct {
	RoomID int32  `json:"room_id"`
	Status string `json:"status"`
}

func (q *Queries) SetRoomStatus(ctx context.Context, arg SetRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomStatus, arg.RoomID, arg.Status)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
	)
	return i, err
}
