// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package repository

import (
	"context"
)

const getFinishedRoom = `-- name: GetFinishedRoom :one
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct FROM rooms
WHERE room_id = $1 AND status = 'finished'
`

type GetFinishedRoomParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetFinishedRoom(ctx context.Context, arg GetFinishedRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, getFinishedRoom, arg.RoomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
	)
	return i, err
}

const getRoundBoosts = `-- name: GetRoundBoosts :many
SELECT room_id, user_id, amount, boosted_at FROM room_boosts
WHERE room_id = $1
ORDER BY boosted_at ASC
`

type GetRoundBoostsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetRoundBoosts(ctx context.Context, arg GetRoundBoostsParams) ([]RoomBoost, error) {
	rows, err := q.db.Query(ctx, getRoundBoosts, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomBoost{}
	for rows.Next() {
		var i RoomBoost
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Amount,
			&i.BoostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoundPlayers = `-- name: GetRoundPlayers :many
SELECT room_id, user_id, places, joined_at FROM room_players
WHERE room_id = $1
ORDER BY joined_at ASC
`

type GetRoundPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetRoundPlayers(ctx context.Context, arg GetRoundPlayersParams) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, getRoundPlayers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPlayer{}
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Places,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoundWinner = `-- name: GetRoundWinner :one
SELECT room_id, user_id, prize, won_at FROM room_winners
WHERE room_id = $1
`

type GetRoundWinnerParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetRoundWinner(ctx context.Context, arg GetRoundWinnerParams) (RoomWinner, error) {
	row := q.db.QueryRow(ctx, getRoundWinner, arg.RoomID)
	var i RoomWinner
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const listFinishedRooms = `-- name: ListFinishedRooms :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct FROM rooms
WHERE status = 'finished'
ORDER BY created_at DESC
`

func (q *Queries) ListFinishedRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listFinishedRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
			&i.WinnerPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
