// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFinishedRoom = `-- name: GetFinishedRoom :one
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type, min_players FROM rooms
WHERE room_id = $1 AND status = 'finished'
`

type GetFinishedRoomParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetFinishedRoom(ctx context.Context, arg GetFinishedRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, getFinishedRoom, arg.RoomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.StartTime,
		&i.Status,
		&i.PlayersNeeded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryCost,
		&i.WinnerPct,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
		&i.MinPlayers,
	)
	return i, err
}

const getRoundBoosts = `-- name: GetRoundBoosts :many
SELECT room_id, user_id, amount, boosted_at FROM room_boosts
WHERE room_id = $1
ORDER BY boosted_at ASC
`

type GetRoundBoostsParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetRoundBoosts(ctx context.Context, arg GetRoundBoostsParams) ([]RoomBoost, error) {
	rows, err := q.db.Query(ctx, getRoundBoosts, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomBoost{}
	for rows.Next() {
		var i RoomBoost
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Amount,
			&i.BoostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoundDetails = `-- name: GetRoundDetails :one
SELECT
    r.room_id,
    r.jackpot,
    r.entry_cost,
    r.winner_pct,
    r.players_needed,
    r.status,
    r.created_at,
    r.start_time,
    COALESCE(
        json_agg(
            DISTINCT jsonb_build_object(
                'user_id', rp.user_id,
                'places', (SELECT COUNT(rp2.place_id)::INTEGER FROM room_players rp2 WHERE rp2.room_id = r.room_id AND rp2.user_id = rp.user_id),
                'joined_at', rp.joined_at
            )
        ) FILTER (WHERE rp.user_id IS NOT NULL),
        '[]'
    ) AS players,
    COALESCE(
        json_agg(
            DISTINCT jsonb_build_object(
                'user_id', rb.user_id,
                'amount', rb.amount,
                'boosted_at', rb.boosted_at
            )
        ) FILTER (WHERE rb.user_id IS NOT NULL),
        '[]'
    ) AS boosts,
    CASE WHEN rw.user_id IS NOT NULL THEN
        jsonb_build_object(
            'user_id', rw.user_id,
            'prize', rw.prize,
            'won_at', rw.won_at
        )
    ELSE NULL END AS winner
FROM rooms r
LEFT JOIN room_players rp ON r.room_id = rp.room_id
LEFT JOIN room_boosts rb ON r.room_id = rb.room_id
LEFT JOIN room_winners rw ON r.room_id = rw.room_id
WHERE r.room_id = $1
GROUP BY r.room_id, rw.user_id, rw.prize, rw.won_at
`

type GetRoundDetailsParams struct {
	RoomID int32 `json:"room_id"`
}

type GetRoundDetailsRow struct {
	RoomID        int32              `json:"room_id"`
	Jackpot       int32              `json:"jackpot"`
	EntryCost     int32              `json:"entry_cost"`
	WinnerPct     int32              `json:"winner_pct"`
	PlayersNeeded int32              `json:"players_needed"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	Players       interface{}        `json:"players"`
	Boosts        interface{}        `json:"boosts"`
	Winner        interface{}        `json:"winner"`
}

func (q *Queries) GetRoundDetails(ctx context.Context, arg GetRoundDetailsParams) (GetRoundDetailsRow, error) {
	row := q.db.QueryRow(ctx, getRoundDetails, arg.RoomID)
	var i GetRoundDetailsRow
	err := row.Scan(
		&i.RoomID,
		&i.Jackpot,
		&i.EntryCost,
		&i.WinnerPct,
		&i.PlayersNeeded,
		&i.Status,
		&i.CreatedAt,
		&i.StartTime,
		&i.Players,
		&i.Boosts,
		&i.Winner,
	)
	return i, err
}

const getRoundPlayers = `-- name: GetRoundPlayers :many
SELECT 
    rp.room_id, 
    rp.user_id, 
    COUNT(rp.place_id)::INTEGER AS places, 
    MIN(rp.joined_at)::TIMESTAMPTZ AS joined_at
FROM room_players rp
WHERE rp.room_id = $1
GROUP BY rp.room_id, rp.user_id
ORDER BY MIN(rp.joined_at) ASC
`

type GetRoundPlayersParams struct {
	RoomID int32 `json:"room_id"`
}

type GetRoundPlayersRow struct {
	RoomID   int32     `json:"room_id"`
	UserID   int32     `json:"user_id"`
	Places   int32     `json:"places"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) GetRoundPlayers(ctx context.Context, arg GetRoundPlayersParams) ([]GetRoundPlayersRow, error) {
	rows, err := q.db.Query(ctx, getRoundPlayers, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoundPlayersRow{}
	for rows.Next() {
		var i GetRoundPlayersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Places,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoundWinner = `-- name: GetRoundWinner :one
SELECT room_id, user_id, prize, won_at FROM room_winners
WHERE room_id = $1
`

type GetRoundWinnerParams struct {
	RoomID int32 `json:"room_id"`
}

func (q *Queries) GetRoundWinner(ctx context.Context, arg GetRoundWinnerParams) (RoomWinner, error) {
	row := q.db.QueryRow(ctx, getRoundWinner, arg.RoomID)
	var i RoomWinner
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Prize,
		&i.WonAt,
	)
	return i, err
}

const listFinishedRooms = `-- name: ListFinishedRooms :many
SELECT room_id, jackpot, start_time, status, players_needed, created_at, updated_at, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type, min_players FROM rooms
WHERE status = 'finished'
ORDER BY created_at DESC
`

func (q *Queries) ListFinishedRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listFinishedRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.Jackpot,
			&i.StartTime,
			&i.Status,
			&i.PlayersNeeded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCost,
			&i.WinnerPct,
			&i.RoundDurationSeconds,
			&i.StartDelaySeconds,
			&i.GameType,
			&i.MinPlayers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
