// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package repository

import (
	"context"
)

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM room_templates
WHERE template_id = $1
`

type DeleteTemplateParams struct {
	TemplateID int32 `json:"template_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.TemplateID)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT template_id, name, players_needed, entry_cost, winner_pct, created_at, updated_at, round_duration_seconds, start_delay_seconds, game_type FROM room_templates
WHERE template_id = $1
`

type GetTemplateParams struct {
	TemplateID int32 `json:"template_id"`
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (RoomTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.TemplateID)
	var i RoomTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.Name,
		&i.PlayersNeeded,
		&i.EntryCost,
		&i.WinnerPct,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO room_templates (name, players_needed, entry_cost, winner_pct, round_duration_seconds, start_delay_seconds, game_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING template_id, name, players_needed, entry_cost, winner_pct, created_at, updated_at, round_duration_seconds, start_delay_seconds, game_type
`

type InsertTemplateParams struct {
	Name                 string `json:"name"`
	PlayersNeeded        int32  `json:"players_needed"`
	EntryCost            int32  `json:"entry_cost"`
	WinnerPct            int32  `json:"winner_pct"`
	RoundDurationSeconds int32  `json:"round_duration_seconds"`
	StartDelaySeconds    int32  `json:"start_delay_seconds"`
	GameType             string `json:"game_type"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (RoomTemplate, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.Name,
		arg.PlayersNeeded,
		arg.EntryCost,
		arg.WinnerPct,
		arg.RoundDurationSeconds,
		arg.StartDelaySeconds,
		arg.GameType,
	)
	var i RoomTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.Name,
		&i.PlayersNeeded,
		&i.EntryCost,
		&i.WinnerPct,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT template_id, name, players_needed, entry_cost, winner_pct, created_at, updated_at, round_duration_seconds, start_delay_seconds, game_type FROM room_templates
ORDER BY created_at DESC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]RoomTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomTemplate{}
	for rows.Next() {
		var i RoomTemplate
		if err := rows.Scan(
			&i.TemplateID,
			&i.Name,
			&i.PlayersNeeded,
			&i.EntryCost,
			&i.WinnerPct,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoundDurationSeconds,
			&i.StartDelaySeconds,
			&i.GameType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE room_templates
SET name = $2,
    players_needed = $3,
    entry_cost = $4,
    winner_pct = $5,
    round_duration_seconds = $6,
    start_delay_seconds = $7,
    game_type = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE template_id = $1
RETURNING template_id, name, players_needed, entry_cost, winner_pct, created_at, updated_at, round_duration_seconds, start_delay_seconds, game_type
`

type UpdateTemplateParams struct {
	TemplateID           int32  `json:"template_id"`
	Name                 string `json:"name"`
	PlayersNeeded        int32  `json:"players_needed"`
	EntryCost            int32  `json:"entry_cost"`
	WinnerPct            int32  `json:"winner_pct"`
	RoundDurationSeconds int32  `json:"round_duration_seconds"`
	StartDelaySeconds    int32  `json:"start_delay_seconds"`
	GameType             string `json:"game_type"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (RoomTemplate, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.TemplateID,
		arg.Name,
		arg.PlayersNeeded,
		arg.EntryCost,
		arg.WinnerPct,
		arg.RoundDurationSeconds,
		arg.StartDelaySeconds,
		arg.GameType,
	)
	var i RoomTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.Name,
		&i.PlayersNeeded,
		&i.EntryCost,
		&i.WinnerPct,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoundDurationSeconds,
		&i.StartDelaySeconds,
		&i.GameType,
	)
	return i, err
}
