// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"
)

const countBots = `-- name: CountBots :one
SELECT COUNT(*) FROM users WHERE bot = true
`

func (q *Queries) CountBots(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBot = `-- name: CreateBot :one
INSERT INTO users (name, balance, bot)
VALUES ($1, $2, true)
RETURNING id, name, balance, created_at, bot
`

type CreateBotParams struct {
	Name    string `json:"name"`
	Balance int32  `json:"balance"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (User, error) {
	row := q.db.QueryRow(ctx, createBot, arg.Name, arg.Balance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, balance)
VALUES ($1, $2)
RETURNING id, name, balance, created_at, bot
`

type CreateUserParams struct {
	Name    string `json:"name"`
	Balance int32  `json:"balance"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Balance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}

const decreaseUserBalance = `-- name: DecreaseUserBalance :one
UPDATE users SET balance = balance - $2
WHERE id = $1 AND balance >= $2 AND $2 >= 0
RETURNING id, name, balance, created_at, bot
`

type DecreaseUserBalanceParams struct {
	ID      int32 `json:"id"`
	Balance int32 `json:"balance"`
}

func (q *Queries) DecreaseUserBalance(ctx context.Context, arg DecreaseUserBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, decreaseUserBalance, arg.ID, arg.Balance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

type DeleteUserParams struct {
	ID int32 `json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, balance, created_at, bot FROM users
WHERE id = $1
`

type GetUserParams struct {
	ID int32 `json:"id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}

const increaseBalanceForLowBalanceBots = `-- name: IncreaseBalanceForLowBalanceBots :exec
UPDATE users
SET balance = balance + $1
WHERE balance < $2 AND bot = true
`

type IncreaseBalanceForLowBalanceBotsParams struct {
	Balance   int32 `json:"balance"`
	Balance_2 int32 `json:"balance_2"`
}

func (q *Queries) IncreaseBalanceForLowBalanceBots(ctx context.Context, arg IncreaseBalanceForLowBalanceBotsParams) error {
	_, err := q.db.Exec(ctx, increaseBalanceForLowBalanceBots, arg.Balance, arg.Balance_2)
	return err
}

const increaseUserBalance = `-- name: IncreaseUserBalance :one
UPDATE users SET balance = balance + $2
WHERE id = $1 AND $2 >= 0
RETURNING id, name, balance, created_at, bot
`

type IncreaseUserBalanceParams struct {
	ID      int32 `json:"id"`
	Balance int32 `json:"balance"`
}

func (q *Queries) IncreaseUserBalance(ctx context.Context, arg IncreaseUserBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, increaseUserBalance, arg.ID, arg.Balance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, balance, created_at, bot FROM users
ORDER BY id ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.CreatedAt,
			&i.Bot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserBalance = `-- name: SetUserBalance :one
UPDATE users SET balance = $2
WHERE id = $1 AND $2 >= 0
RETURNING id, name, balance, created_at, bot
`

type SetUserBalanceParams struct {
	ID      int32 `json:"id"`
	Balance int32 `json:"balance"`
}

func (q *Queries) SetUserBalance(ctx context.Context, arg SetUserBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserBalance, arg.ID, arg.Balance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}

const updateUserBalance = `-- name: UpdateUserBalance :one
UPDATE users SET balance = balance + $2
WHERE id = $1 AND balance + $2 >= 0
RETURNING id, name, balance, created_at, bot
`

type UpdateUserBalanceParams struct {
	ID      int32 `json:"id"`
	Balance int32 `json:"balance"`
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserBalance, arg.ID, arg.Balance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.Bot,
	)
	return i, err
}
