import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  container: {
    width: '100vw',
    height: '100vh',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    color: '#fff',
    fontFamily: 'Inter, system-ui, sans-serif',
    overflowY: 'auto',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
    zIndex: 0,
  },
  timerHeader: {
    zIndex: 1,
    marginTop: 20,
    background: 'rgba(0,0,0,0.85)',
    padding: '10px 25px',
    borderRadius: '14px',
    fontSize: '20px',
    fontWeight: 'bold',
    border: '1px solid rgba(255,255,255,0.1)',
  },
  mainContent: {
    zIndex: 1,
    display: 'flex',
    width: '95%',
    maxWidth: '1700px',
    justifyContent: 'space-around',
    alignItems: 'center',
    flex: 1,
    gap: '40px',
  },
  fridgeWrapper: { width: '800px', textAlign: 'center' },
  videoContainer: {
    width: '100%',
    minHeight: '600px',
    background: 'transparent',
    borderRadius: '32px',
    overflow: 'hidden',
  },
  instruction: {
    fontSize: '24px',
    marginBottom: '20px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  fridgeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 140px)',
    gap: '20px',
    padding: '40px',
    backgroundSize: 'contain',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
    minHeight: '1000px',
    justifyContent: 'center',
    alignContent: 'center',
  },
  cell: {
    height: '65px',
    width: '130px',
    border: '2px solid #FF008A',
    borderRadius: '12px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '24px',
    fontWeight: 'bold',
    transition: '0.2s',
  },
  infoPanel: {
    width: '420px',
    background: 'rgba(10, 10, 10, 0.8)',
    backdropFilter: 'blur(25px)',
    borderRadius: '32px',
    padding: '40px',
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
    border: '1px solid rgba(255,255,255,0.08)',
  },
  statBox: { textAlign: 'center' },
  label: { opacity: 0.5, fontSize: '14px', textTransform: 'uppercase' },
  bankValue: { display: 'block', fontSize: '42px', color: '#FFD700', fontWeight: 900 },
  mainValue: { display: 'block', fontSize: '34px', fontWeight: 800 },
  subLabel: { fontSize: '13px', opacity: 0.4 },
  actionContainer: { marginTop: '10px' },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    background: '#181818',
    borderRadius: '18px',
    padding: '8px 12px',
    border: '1px solid #333',
  },
  input: {
    background: 'transparent',
    border: 'none',
    color: '#fff',
    flex: 1,
    padding: '12px',
    outline: 'none',
    fontSize: '16px',
  },
  plusBtn: {
    background: '#FF008A',
    border: 'none',
    width: '48px',
    height: '48px',
    borderRadius: '14px',
    color: '#fff',
    fontSize: '28px',
    cursor: 'pointer',
  },
  activeBonusBar: {
    background: '#B4F05A',
    height: '60px',
    borderRadius: '18px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 0 20px rgba(180, 240, 90, 0.3)',
  },
  sidebar: {
    background: 'rgba(0,0,0,0.8)',
    padding: '24px 14px',
    borderRadius: '28px',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  avatarBorder: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    border: '3px solid #FF008A',
    overflow: 'hidden',
  },
  avatar: { width: '100%', height: '100%', objectFit: 'cover' },
  navArrow: { textAlign: 'center', opacity: 0.4, fontSize: '14px' },
  modalBackdrop: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.92)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    backdropFilter: 'blur(10px)',
  },
  modalCard: {
    width: '600px',
    background: '#050505',
    padding: '45px',
    borderRadius: '32px',
    border: '1px solid #222',
  },
  modalTitle: { textAlign: 'center', marginBottom: '35px', fontSize: '28px' },
  leaderboard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '35px',
  },
  rowPlayer: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '16px 24px',
    borderBottom: '1px solid #151515',
  },
  rowUser: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '18px 24px',
    background: '#B4F05A',
    color: '#000',
    borderRadius: '16px',
    fontWeight: 'bold',
  },
  btnGroup: { display: 'flex', gap: '20px', justifyContent: 'center' },
  restartBtn: {
    background: '#FF008A',
    color: '#fff',
    padding: '18px 36px',
    border: 'none',
    borderRadius: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    fontSize: '16px',
  },
  exitBtn: {
    background: '#222',
    color: '#fff',
    padding: '18px 36px',
    border: 'none',
    borderRadius: '16px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  canvas: { width: '100%', height: 'auto', display: 'block' },
}
